# docker-compose.yml

version: '3'

networks:
  network:
    driver: bridge

services:

  ## ================== NGINX
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
      args:
        version: ${NG_VERSION}
        working_dir: ${WORKING_DIR}
    container_name: "nginx-${APP_ENV}"
    restart: unless-stopped
    tty: true
    ports:
      - "${NG_PORT}:80"
    networks:
      - network
    working_dir: ${WORKING_DIR}
    links:
      - php

  ## ================== PHP
  php:
    build:
      context: .
      dockerfile: containers/php/Dockerfile
      args:
        version: ${PHP_VERSION}
        working_dir: ${WORKING_DIR}
    container_name: "php-${APP_ENV}"
    ports:
      - "9000"
    networks:
      - network
    working_dir: ${WORKING_DIR}

  ## ================== Workspace
  workspace:
    build:
      context: .
      dockerfile: containers/workspace/Dockerfile
      args:
        version: ${PHP_VERSION}
        working_dir: ${WORKING_DIR}
    container_name: "workspace-${APP_ENV}"
    tty: true
    networks:
      - network
    working_dir: ${WORKING_DIR}

