# docker-compose.yml

version: '3.7'

networks:
  network:
    driver: bridge
    name: "network-${APP_ENV}-${APP_NAME}-${APP_VERSION}"

services:

  ## ================== APP
  app:
    image: "app-${APP_ENV}-${APP_NAME}-${APP_VERSION}"
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
      args:
        version_php: ${PHP_VERSION}
        version_tag: ${PHP_VERSION}${PHP_TAG}
        working_dir: ${WORKING_DIR}
    container_name: "app-${APP_ENV}-${APP_NAME}-${APP_VERSION}"
    ports:
      - ${PHP_EXTERNAL_PORT}
    networks:
      - network
    working_dir: ${WORKING_DIR}

  ## ================== SERVER
  server:
    image: "server-${APP_ENV}-${APP_NAME}-${APP_VERSION}"
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
      args:
        version_tag: ${NGINX_VERSION}${NGINX_TAG}
    container_name: "server-${APP_ENV}-${APP_NAME}-${APP_VERSION}"
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    networks:
      - network
    working_dir: /etc/nginx
    links:
      - app

