# docker-compose.yml

version: '3.7'

networks:
  network:
    driver: bridge

services:

  ## ================== APP
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
      args:
        version_php: ${PHP_VERSION}
        version_tag: ${PHP_VERSION}${PHP_TAG}
        working_dir: ${WORKING_DIR}
        php_port: ${PHP_PORT}
        max_file_size: ${MAX_FILE_SIZE_UPLOAD}
    ports:
      - ${PHP_PORT}
    networks:
      - network
    working_dir: ${WORKING_DIR}

  ## ================== SERVER
  server:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
      args:
        version_tag: ${NGINX_VERSION}${NGINX_TAG}
        nginx_port: ${NGINX_PORT}
        working_dir: ${WORKING_DIR}
        php_port: ${PHP_PORT}
        php_container: "app"
        max_file_size: ${MAX_FILE_SIZE_UPLOAD}
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_PORT}"
    networks:
      - network
    working_dir: /etc/nginx
    links:
      - app

