# docker-compose.yml

version: '3'

services:

  ### Nginx Container
  nginx:
    build: docker/nginx
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www

      - ./docker/nginx/conf.d/default:/etc/nginx/conf.d/default.conf

      - ./docker/nginx/logs/nginx-error.log:/var/log/nginx/error.log
      - ./docker/nginx/logs/nginx-access.log:/var/log/nginx/access.log
    links:
      - php

  ### PHP Container
  php:
    build: docker/php
    ports:
      - "9000"
    volumes:
      - ./:/var/www
    links:
      - mysql

  ### MySQL Container
  mysql:
    build: docker/mysql
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "13306:${DB_PORT?Missing DB_PORT variable in .env}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE?Missing DB_DATABASE variable in .env}
      DB_USERNAME: ${DB_USERNAME?Missing DB_USERNAME variable in .env}
      MYSQL_PASSWORD: ${DB_PASSWORD?Missing DB_PASSWORD variable in .env}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?Missing DB_PASSWORD variable in .env}

  ### Workspace Utilities Container
  workspace:
    build: docker/workspace
    volumes:
      - ./:/var/www
      - ./docker/mysql/import/database.sql.gz:/tmp/mysql/database.sql.gz
    links:
      - mysql
    tty: true