# docker-compose.yml

version: '3'

services:

  ### Nginx Container
  nginx:
    build: nginx
    image: nginx:${NG_VERSION}
    ports:
      - "${NG_PORT}:80"
    volumes:
      - ./../:/var/www

      - ./nginx/conf.d/default:/etc/nginx/conf.d/default.conf

      - ./nginx/logs/nginx-error.log:/var/log/nginx/error.log
      - ./nginx/logs/nginx-access.log:/var/log/nginx/access.log
    links:
      - php

  ### PHP Container
  php:
    build: php
    image: php:${PHP_VERSION}
    ports:
      - "9000"
    volumes:
      - ./../:/var/www
    links:
      - mysql

  ### MySQL Container
  mysql:
    build: mysql
    image: mysql:${DB_VERSION}
    volumes:
      - /var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "13306:${DB_PORT?Missing DB_PORT variable in .env.example}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE?Missing DB_DATABASE variable in .env}
      MYSQL_USER: ${DB_USERNAME?Missing DB_USERNAME variable in .env}
      MYSQL_PASSWORD: ${DB_PASSWORD?Missing DB_PASSWORD variable in .env}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?Missing DB_PASSWORD variable in .env}

  ### Workspace Utilities Container
  workspace:
    build: workspace
    volumes:
      - ./../:/var/www
    links:
      - mysql
    tty: true